In [27]:
import pandas as pd

In [28]:
# read main table with human and mouse genes into a pandas dataframe

# path for Windows
human_mouse_genes = pd.read_csv("c:\\Users\\pmbog\\source\\Main_project\\genotype_to_phenotype\\database_creation\\db_1_hum_mouse_genes.csv", delimiter="\t")

# path for Ubuntu
# human_mouse_genes = pd.read_csv(".\database_creation\db_1_hum_mouse_genes.csv", delimiter="\t")

human_mouse_genes

,Unnamed: 0,gene_human,entrez_id_human,gene_mouse,MGI,MP
0,0,A1BG,1,A1bg,MGI:2152878,NaN
1,1,A1CF,29974,A1cf,MGI:1917115,"MP:0005367, MP:0005369, MP:0005370, MP:0005376..."
2,2,A2M,2,A2m,MGI:2449119,NaN
3,3,A3GALT2,127550,A3galt2,MGI:2685279,NaN
4,4,A4GALT,53947,A4galt,MGI:3512453,"MP:0005376, MP:0005386, MP:0010768"
...,...,...,...,...,...,...
29681,29681,ZYG11A,440590,Zyg11a,MGI:2446208,NaN
29682,29682,ZYG11B,79699,Zyg11b,MGI:2685277,"MP:0005386, MP:0010768"
29683,29683,ZYX,7791,Zyx,MGI:103072,MP:0005384
29684,29684,ZZEF1,23140,Zzef1,MGI:2444286,"MP:0005367, MP:0005378, MP:0005386, MP:0005390..."
29685,29685,ZZZ3,26009,Zzz3,MGI:1920453,NaN

In [29]:
# read table with human phenotype and HPO-terms into a pandas dataframe and leave only columns with genes and phenotypes

# path for Windows
human_HPO_table = pd.read_csv("c:\\Users\\pmbog\\source\\Main_project\\genotype_to_phenotype\\databases\\genes_to_phenotype.txt", delimiter="\t", skiprows=1, header=None, usecols=range(0,4))\
    .rename(columns={0: "entrez_id_human", 1: "entrez-gene-symboln", 2: "HPO-Term-ID", 3: "HPO-Term-Name"})

# path for Ubuntu
# human_HPO_table = pd.read_csv(".\databases\genes_to_phenotype.txt", delimiter="\t", skiprows=1, header=None, usecols=range(0,4))\
#   .rename(columns={0: "entrez_id_human", 1: "entrez-gene-symboln", 2: "HPO-Term-ID", 3: "HPO-Term-Name"})

human_HPO_table

,entrez_id_human,entrez-gene-symboln,HPO-Term-ID,HPO-Term-Name
0,8192,CLPP,HP:0000013,Hypoplasia of the uterus
1,8192,CLPP,HP:0000815,Hypergonadotropic hypogonadism
2,8192,CLPP,HP:0000786,Primary amenorrhea
3,8192,CLPP,HP:0000007,Autosomal recessive inheritance
4,8192,CLPP,HP:0000252,Microcephaly
...,...,...,...,...
268978,57338,JPH3,HP:0004302,Functional motor deficit
268979,57338,JPH3,HP:0000751,Personality changes
268980,57338,JPH3,HP:0002354,Memory impairment
268981,57338,JPH3,HP:0000726,Dementia
268982,57338,JPH3,HP:0002120,Cerebral cortical atrophy

In [30]:
# combine genes by HPO terms and HPO terms names

human_HPO_table = human_HPO_table.groupby("entrez_id_human").agg({"HPO-Term-ID": list, "HPO-Term-Name": list}).reset_index()
human_HPO_table

,entrez_id_human,HPO-Term-ID,HPO-Term-Name
0,16,"[HP:0012377, HP:0030903, HP:0010871, HP:000072...","[Hemianopia, Grasp reflex, Sensory ataxia, Dem..."
1,18,"[HP:0000098, HP:0000494, HP:0001321, HP:000125...","[Tall stature, Downslanted palpebral fissures,..."
2,19,"[HP:0001681, HP:0007759, HP:0001114, HP:000323...","[Angina pectoris, Opacification of the corneal..."
3,20,"[HP:0002066, HP:0002311, HP:0000252, HP:000051...","[Gait ataxia, Incoordination, Microcephaly, De..."
4,21,"[HP:0025179, HP:0002875, HP:0006517, HP:002539...","[Ground-glass opacification, Exertional dyspne..."
...,...,...,...
4890,105259599,"[HP:0001428, HP:0002667, HP:0000006, HP:000818...","[Somatic mutation, Nephroblastoma, Autosomal d..."
4891,105371045,"[HP:0000588, HP:0000951, HP:0000737, HP:000194...","[Optic disc coloboma, Abnormality of the skin,..."
4892,109580095,"[HP:0011906, HP:0004840]","[Reduced beta/alpha synthesis ratio, Hypochrom..."
4893,111365204,"[HP:0007663, HP:0000603, HP:0200070, HP:000775...","[Reduced visual acuity, Central scotoma, Perip..."
4894,120766137,"[HP:0003577, HP:0000006, HP:0002209, HP:000065...","[Congenital onset, Autosomal dominant inherita..."

In [32]:
# concatenate the list of HPOs into a string variable
human_HPO_table["HPO-Term-ID"] = human_HPO_table["HPO-Term-ID"].apply(lambda x: ', '.join(x))
human_HPO_table["HPO-Term-Name"] = human_HPO_table["HPO-Term-Name"].apply(lambda x: ', '.join(x))
human_HPO_table

,entrez_id_human,HPO-Term-ID,HPO-Term-Name
0,16,"HP:0012377, HP:0030903, HP:0010871, HP:0000726...","Hemianopia, Grasp reflex, Sensory ataxia, Deme..."
1,18,"HP:0000098, HP:0000494, HP:0001321, HP:0001250...","Tall stature, Downslanted palpebral fissures, ..."
2,19,"HP:0001681, HP:0007759, HP:0001114, HP:0003233...","Angina pectoris, Opacification of the corneal ..."
3,20,"HP:0002066, HP:0002311, HP:0000252, HP:0000519...","Gait ataxia, Incoordination, Microcephaly, Dev..."
4,21,"HP:0025179, HP:0002875, HP:0006517, HP:0025391...","Ground-glass opacification, Exertional dyspnea..."
...,...,...,...
4890,105259599,"HP:0001428, HP:0002667, HP:0000006, HP:0008186...","Somatic mutation, Nephroblastoma, Autosomal do..."
4891,105371045,"HP:0000588, HP:0000951, HP:0000737, HP:0001944...","Optic disc coloboma, Abnormality of the skin, ..."
4892,109580095,"HP:0011906, HP:0004840","Reduced beta/alpha synthesis ratio, Hypochromi..."
4893,111365204,"HP:0007663, HP:0000603, HP:0200070, HP:0007754...","Reduced visual acuity, Central scotoma, Periph..."
4894,120766137,"HP:0003577, HP:0000006, HP:0002209, HP:0000653...","Congenital onset, Autosomal dominant inheritan..."

In [33]:
# combine the main table with the genes of both mice and humans and the table with the human phenotype by Entrez Gene ID
db_3_human = pd.merge(human_mouse_genes, human_HPO_table, how='left', on = 'entrez_id_human')
db_3_human

,Unnamed: 0,gene_human,entrez_id_human,gene_mouse,MGI,MP,HPO-Term-ID,HPO-Term-Name
0,0,A1BG,1,A1bg,MGI:2152878,NaN,NaN,NaN
1,1,A1CF,29974,A1cf,MGI:1917115,"MP:0005367, MP:0005369, MP:0005370, MP:0005376...",NaN,NaN
2,2,A2M,2,A2m,MGI:2449119,NaN,NaN,NaN
3,3,A3GALT2,127550,A3galt2,MGI:2685279,NaN,NaN,NaN
4,4,A4GALT,53947,A4galt,MGI:3512453,"MP:0005376, MP:0005386, MP:0010768","HP:0000006, HP:0010970","Autosomal dominant inheritance, Blood group an..."
...,...,...,...,...,...,...,...,...
29681,29681,ZYG11A,440590,Zyg11a,MGI:2446208,NaN,NaN,NaN
29682,29682,ZYG11B,79699,Zyg11b,MGI:2685277,"MP:0005386, MP:0010768",NaN,NaN
29683,29683,ZYX,7791,Zyx,MGI:103072,MP:0005384,NaN,NaN
29684,29684,ZZEF1,23140,Zzef1,MGI:2444286,"MP:0005367, MP:0005378, MP:0005386, MP:0005390...",NaN,NaN
29685,29685,ZZZ3,26009,Zzz3,MGI:1920453,NaN,NaN,NaN

In [34]:
# save the table in csv file
db_3_human.to_csv("db_3_human.csv", sep="\t")